### ISSUE TITLE
Bubble menu glitches when the editor changes positions

### ISSUE THREAD

**Issue by jesteracer** [sibiraj-s/svelte-tiptap#5] opened 2022-02-18 20:55 UTC
Hey, first of all thanks for the great work

I am trying to wrap my head around bubble menu glitch, that you can check out here https://svelte.dev/repl/89cf6d5d4017435b8b7474c088057ff4?version=3.46.4

If there are many instances of tiptap and they get remounted (like if the positions change) the bubble menu gets rendered with a style "visibility: visible;" (if you click on the tiptap editor after that it goes away)

I can't find a way to make it not do that :(

**Comment by sibiraj-s** [comment] 2022-02-19 17:43
Hi @jesteracer. I can see the bug. Tried to locate it, but there seems to be nothing wrong here. 

It could be with tiptap itself. Took a shortcut to verify this, I tried reproducing this with tiptap's react package. It happens there as well.

**Comment by jesteracer** [comment] 2022-02-21 04:44
I kind of "fixed" it (updated the example code), by just wrapping the <BubbleMenu> with a div with dispay:none property
Since inside this lib there is also a div, that wrapps the actual component maybe you can add this to the library — it should not break things

**Comment by sibiraj-s** [comment] 2022-02-21 05:12
Thanks. Nice workaround 👍 . 

> Since inside this lib there is also a div, that wrapps the actual component maybe you can add this to the library 

Maybe If nothing works, First Let's see if this bug can be fixed.

**Comment by leerobert** [comment] 2023-05-25 16:26
I think you need to add type="button" to the buttons as well.

**Comment by sibiraj-s** [comment] 2023-07-02 06:47
There are two options to solve this.

1.  wrap a div around bubble menu with display none property, See https://github.com/sibiraj-s/svelte-tiptap/issues/5#issuecomment-1046469762

```jsx
<div style="display:none;">
   <BubbleMenu editor={$editor}></BubbleMenu>
</div>
```

2. Move the BubbleMenu inside EditorContent (Requires v1.1.0)

```jsx
<EditorContent editor={$editor}>
   <BubbleMenu editor={$editor}></BubbleMenu>
</EditorContent>
```

Since this is a bug in the bubble menu plugin itself. Closing this issue. There is an open issue to track this https://github.com/ueberdosis/tiptap/issues/2568

**Closed by sibiraj-s** 2023-07-02 06:47 UTC
