### ISSUE TITLE
handling unused props with `SvelteNodeViewRenderer`

### ISSUE THREAD

**Issue by ronkeiser** [sibiraj-s/svelte-tiptap#36] opened 2023-09-27 15:43 UTC
When adding node views with `SvelteNodeViewRenderer`, the node component is passed all of the `NodeViewProps` as individual props which creates unknown prop errors like this:

`<NodeComponent> was created with unknown prop 'editor'`

Is it possible to pass only the props which are exported by the component? Is there another recommended way to handle `NodeViewProps` keys that are not used?

**Comment by sibiraj-s** [comment] 2023-09-28 06:46
Yeah its annoying. The problem with this is that, we don't know what the component would use. hence passing all. I can't think of anything ATM. Open to suggestions.

May be context? 🤔

**Comment by aivo0** [comment] 2023-09-28 07:12
I declare all possible props in the component  with export let. That removes the runtime warnings from user's console. Still get build time warnings like the following, but it's much better than constant runtime warnings on every component render:
[vite-plugin-svelte] /src/lib/components/nodes/components/Sub.svelte:11:11 Sub has unused export property 'decorations'. If it is for external reference only, please consider using `export const decorations`

**Comment by ronkeiser** [comment] 2023-09-28 08:25
Hmm, what about consolidating to a single prop?

`export let nodeViewProps: NodeViewProps` 


I also found this thread with a related discussion: https://github.com/sveltejs/svelte/issues/4652

A user recently suggested adding `$$restProps`  as a workaround. This of course does work, but it feels very dirty to add this to every node component just to avoid compiler warnings.

**Comment by sibiraj-s** [comment] 2023-10-03 14:08
> Hmm, what about consolidating to a single prop?

Would require a breaking change, but makes sense. 

For now, the workaround can be used. I'll try to work on something this weekend.

**Comment by einarpersson** [comment] 2023-12-09 14:06
> Hmm, what about consolidating to a single prop?
> 
> `export let nodeViewProps: NodeViewProps`
> 
> I also found this thread with a related discussion: [sveltejs/svelte#4652](https://github.com/sveltejs/svelte/issues/4652)
> 
> A user recently suggested adding `$$restProps` as a workaround. This of course does work, but it feels very dirty to add this to every node component just to avoid compiler warnings. But maybe there's some better way to use it?

How would you use `$$restProps` here without causing another warning/lint-warning? (since I don't "need" it)

**Comment by sibiraj-s** [comment] 2023-12-10 02:46
May be this will be fixed in svelte 5. 

See https://svelte.dev/blog/runes#runtime-reactivity

you could do something like.

```ts
let nodeViewProps = $props()
```

**Comment by sibiraj-s** [comment] 2024-05-11 01:40
Svelte 5 is in release candidate and the [$props() api](https://svelte-5-preview.vercel.app/docs/old-vs-new#simple-component-props) is confirmed.

Closing this issue in favor of the $props api in svelte 5 and the library needs no changes.

**Closed by sibiraj-s** 2024-05-11 01:40 UTC
